[package]
name = "papeline-join"
version.workspace = true
edition.workspace = true

[dependencies]
duckdb.workspace = true
anyhow.workspace = true
log.workspace = true
glob.workspace = true

[dev-dependencies]
tempfile.workspace = true
env_logger.workspace = true
duckdb.workspace = true
